// Generated by CoffeeScript 1.7.1
(function() {
  var CLIENT_ID, SCOPES;

  CLIENT_ID = '750901531017-o1tkotf27ckopad2516dfcc1qeok9oq3.apps.googleusercontent.com';

  SCOPES = ['https://www.googleapis.com/auth/drive.file', 'https://www.googleapis.com/auth/userinfo.email', 'https://www.googleapis.com/auth/userinfo.profile'];

  gapi.load("auth:client,drive-realtime,drive-share", function() {
    var auth_response;
    auth_response = function(response) {
      var error, init, loaded;
      if (!response) {
        return gapi.auth.authorize({
          'client_id': CLIENT_ID,
          'scope': SCOPES,
          'immediate': false
        }, auth_response);
      } else {
        loaded = function() {
          return console.log('loaded');
        };
        init = function() {
          return console.log('init');
        };
        error = function() {
          return console.log('error');
        };
        return gapi.drive.realtime.load('chat1', loaded, init, error);
      }
    };
    return gapi.auth.authorize({
      'client_id': CLIENT_ID,
      'scope': SCOPES.join(' '),
      'immediate': true
    }, auth_response);
  });

}).call(this);
